// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msp/channel.proto

package msp

import (
	fmt "fmt"
	common "github.com/elforg/elfplatform/protos/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Channel struct {
	Value                *ChannelValue  `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Policy               *common.Policy `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
	IncludeMenu          *common.Menu   `protobuf:"bytes,3,opt,name=include_menu,json=includeMenu,proto3" json:"include_menu,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Channel) Reset()         { *m = Channel{} }
func (m *Channel) String() string { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()    {}
func (*Channel) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec99a7156eebaf87, []int{0}
}

func (m *Channel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Channel.Unmarshal(m, b)
}
func (m *Channel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Channel.Marshal(b, m, deterministic)
}
func (m *Channel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Channel.Merge(m, src)
}
func (m *Channel) XXX_Size() int {
	return xxx_messageInfo_Channel.Size(m)
}
func (m *Channel) XXX_DiscardUnknown() {
	xxx_messageInfo_Channel.DiscardUnknown(m)
}

var xxx_messageInfo_Channel proto.InternalMessageInfo

func (m *Channel) GetValue() *ChannelValue {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Channel) GetPolicy() *common.Policy {
	if m != nil {
		return m.Policy
	}
	return nil
}

func (m *Channel) GetIncludeMenu() *common.Menu {
	if m != nil {
		return m.IncludeMenu
	}
	return nil
}

type ChannelValue struct {
	Metadata             *common.Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ChannelValue) Reset()         { *m = ChannelValue{} }
func (m *ChannelValue) String() string { return proto.CompactTextString(m) }
func (*ChannelValue) ProtoMessage()    {}
func (*ChannelValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec99a7156eebaf87, []int{1}
}

func (m *ChannelValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelValue.Unmarshal(m, b)
}
func (m *ChannelValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelValue.Marshal(b, m, deterministic)
}
func (m *ChannelValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelValue.Merge(m, src)
}
func (m *ChannelValue) XXX_Size() int {
	return xxx_messageInfo_ChannelValue.Size(m)
}
func (m *ChannelValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelValue.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelValue proto.InternalMessageInfo

func (m *ChannelValue) GetMetadata() *common.Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterType((*Channel)(nil), "msp.Channel")
	proto.RegisterType((*ChannelValue)(nil), "msp.ChannelValue")
}

func init() { proto.RegisterFile("msp/channel.proto", fileDescriptor_ec99a7156eebaf87) }

var fileDescriptor_ec99a7156eebaf87 = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x4f, 0x4b, 0x04, 0x21,
	0x18, 0xc6, 0x99, 0x96, 0xb6, 0x70, 0x87, 0x68, 0x8c, 0x60, 0xd8, 0x53, 0xec, 0xa1, 0x96, 0x08,
	0x85, 0xba, 0x76, 0xaa, 0x73, 0x10, 0x1e, 0x3a, 0x74, 0x09, 0xd7, 0x75, 0x67, 0x06, 0x7c, 0x55,
	0x46, 0x0d, 0xfa, 0x0c, 0x7d, 0xe9, 0xf0, 0xcf, 0x4c, 0x7b, 0x52, 0x7f, 0xcf, 0xcf, 0xd7, 0x47,
	0xd4, 0x80, 0xb3, 0x54, 0xf4, 0x5c, 0x6b, 0xa9, 0x88, 0x1d, 0x8d, 0x37, 0x78, 0x01, 0xce, 0xae,
	0x1b, 0x61, 0x00, 0x8c, 0xa6, 0x20, 0x75, 0xc8, 0x7c, 0x7d, 0x55, 0x90, 0x35, 0x6a, 0x10, 0x3f,
	0x05, 0x5e, 0xcf, 0x9e, 0xe7, 0x7b, 0xee, 0x79, 0xc6, 0x9b, 0xdf, 0x0a, 0x9d, 0xbd, 0xe6, 0xa9,
	0xf8, 0x0e, 0x9d, 0x7e, 0x73, 0x15, 0x64, 0x5b, 0xdd, 0x54, 0xdb, 0xd5, 0x63, 0x43, 0xc0, 0x59,
	0x52, 0xc2, 0x8f, 0x18, 0xb0, 0x9c, 0xe3, 0x5b, 0xb4, 0xcc, 0xb3, 0xdb, 0x93, 0x64, 0x5e, 0x90,
	0x3c, 0x9c, 0xbc, 0x27, 0xca, 0x4a, 0x8a, 0x29, 0xaa, 0x07, 0x2d, 0x54, 0xd8, 0xcb, 0xaf, 0x58,
	0xaf, 0x5d, 0x24, 0xbb, 0x9e, 0xec, 0x37, 0xa9, 0x03, 0x5b, 0x15, 0x23, 0x1e, 0x36, 0xcf, 0xa8,
	0x3e, 0x7e, 0x0f, 0x3f, 0xa0, 0xf3, 0xa9, 0x6f, 0x29, 0x75, 0xf9, 0x7f, 0x39, 0x73, 0x36, 0x1b,
	0x2f, 0xf7, 0x9f, 0xdb, 0x6e, 0xf0, 0x7d, 0xd8, 0x45, 0x87, 0x4a, 0x75, 0x30, 0x63, 0x17, 0x17,
	0xab, 0xb8, 0x3f, 0x98, 0x11, 0x68, 0xfa, 0xb2, 0xa3, 0xe0, 0xec, 0x6e, 0x99, 0xf6, 0x4f, 0x7f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x65, 0x11, 0x03, 0xb7, 0x57, 0x01, 0x00, 0x00,
}
