// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msp/organization.proto

package msp

import (
	fmt "fmt"
	common "github.com/elforg/elfplatform/protos/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Organization struct {
	Value                *OrgValue       `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Policy               *common.Policy  `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
	SubOrg               []*Organization `protobuf:"bytes,3,rep,name=sub_org,json=subOrg,proto3" json:"sub_org,omitempty"`
	IncludeChannel       []*Channel      `protobuf:"bytes,4,rep,name=include_channel,json=includeChannel,proto3" json:"include_channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Organization) Reset()         { *m = Organization{} }
func (m *Organization) String() string { return proto.CompactTextString(m) }
func (*Organization) ProtoMessage()    {}
func (*Organization) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6f9a53b68b201bf, []int{0}
}

func (m *Organization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Organization.Unmarshal(m, b)
}
func (m *Organization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Organization.Marshal(b, m, deterministic)
}
func (m *Organization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Organization.Merge(m, src)
}
func (m *Organization) XXX_Size() int {
	return xxx_messageInfo_Organization.Size(m)
}
func (m *Organization) XXX_DiscardUnknown() {
	xxx_messageInfo_Organization.DiscardUnknown(m)
}

var xxx_messageInfo_Organization proto.InternalMessageInfo

func (m *Organization) GetValue() *OrgValue {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Organization) GetPolicy() *common.Policy {
	if m != nil {
		return m.Policy
	}
	return nil
}

func (m *Organization) GetSubOrg() []*Organization {
	if m != nil {
		return m.SubOrg
	}
	return nil
}

func (m *Organization) GetIncludeChannel() []*Channel {
	if m != nil {
		return m.IncludeChannel
	}
	return nil
}

type OrgValue struct {
	Metadata             *common.Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *OrgValue) Reset()         { *m = OrgValue{} }
func (m *OrgValue) String() string { return proto.CompactTextString(m) }
func (*OrgValue) ProtoMessage()    {}
func (*OrgValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6f9a53b68b201bf, []int{1}
}

func (m *OrgValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrgValue.Unmarshal(m, b)
}
func (m *OrgValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrgValue.Marshal(b, m, deterministic)
}
func (m *OrgValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrgValue.Merge(m, src)
}
func (m *OrgValue) XXX_Size() int {
	return xxx_messageInfo_OrgValue.Size(m)
}
func (m *OrgValue) XXX_DiscardUnknown() {
	xxx_messageInfo_OrgValue.DiscardUnknown(m)
}

var xxx_messageInfo_OrgValue proto.InternalMessageInfo

func (m *OrgValue) GetMetadata() *common.Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterType((*Organization)(nil), "msp.Organization")
	proto.RegisterType((*OrgValue)(nil), "msp.OrgValue")
}

func init() { proto.RegisterFile("msp/organization.proto", fileDescriptor_d6f9a53b68b201bf) }

var fileDescriptor_d6f9a53b68b201bf = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x5f, 0x4b, 0xc3, 0x30,
	0x14, 0xc5, 0x99, 0xd5, 0x3a, 0xb2, 0x39, 0x5d, 0x44, 0x29, 0x7b, 0x1a, 0x13, 0xa4, 0x0c, 0x69,
	0x61, 0x22, 0xf8, 0xac, 0xcf, 0x52, 0xe9, 0x83, 0x0f, 0xbe, 0x8c, 0xb4, 0xeb, 0xb2, 0x40, 0x92,
	0x1b, 0xf2, 0x47, 0xd0, 0x0f, 0xe7, 0x67, 0x93, 0x26, 0xe9, 0xf0, 0xa9, 0xcd, 0xef, 0x9c, 0x7b,
	0xee, 0xe1, 0xa2, 0x5b, 0x61, 0x54, 0x09, 0x9a, 0x12, 0xc9, 0x7e, 0x88, 0x65, 0x20, 0x0b, 0xa5,
	0xc1, 0x02, 0x4e, 0x84, 0x51, 0x8b, 0x9b, 0x16, 0x84, 0x00, 0x59, 0x8a, 0xce, 0x92, 0x1d, 0xb1,
	0x24, 0x68, 0x8b, 0xeb, 0x88, 0x15, 0x70, 0xd6, 0x7e, 0x47, 0x38, 0xef, 0x83, 0xda, 0x03, 0x91,
	0xb2, 0xe3, 0x01, 0xad, 0x7e, 0x47, 0x68, 0x5a, 0xfd, 0x8b, 0xc6, 0x77, 0xe8, 0xec, 0x8b, 0x70,
	0xd7, 0x65, 0xa3, 0xe5, 0x28, 0x9f, 0x6c, 0x2e, 0x0a, 0x61, 0x54, 0x51, 0x69, 0xfa, 0xd1, 0xc3,
	0x3a, 0x68, 0xf8, 0x1e, 0xa5, 0x21, 0x38, 0x3b, 0xf1, 0xae, 0x59, 0x11, 0xd6, 0x15, 0xef, 0x9e,
	0xd6, 0x51, 0xc5, 0x6b, 0x74, 0x6e, 0x5c, 0xb3, 0x05, 0x4d, 0xb3, 0x64, 0x99, 0xe4, 0x93, 0xcd,
	0x7c, 0x88, 0x3b, 0x2e, 0xac, 0x53, 0xe3, 0x9a, 0x4a, 0x53, 0xfc, 0x84, 0x2e, 0x99, 0x6c, 0xb9,
	0xdb, 0x75, 0xdb, 0x58, 0x31, 0x3b, 0xf5, 0x33, 0x53, 0x3f, 0xf3, 0x1a, 0x58, 0x3d, 0x8b, 0xa6,
	0xf8, 0x5e, 0x3d, 0xa3, 0xf1, 0xd0, 0x0e, 0x3f, 0xa0, 0xf1, 0x70, 0x86, 0x58, 0xff, 0x6a, 0x28,
	0xf6, 0x16, 0x79, 0x7d, 0x74, 0xbc, 0xac, 0x3f, 0x73, 0xca, 0xec, 0xc1, 0x35, 0xbd, 0xa7, 0xec,
	0xf8, 0x1e, 0x34, 0xed, 0x3f, 0x8a, 0x13, 0xbb, 0x07, 0x2d, 0x4a, 0x7f, 0x21, 0x53, 0x0a, 0xa3,
	0x9a, 0xd4, 0xff, 0x3f, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0x47, 0xdc, 0x7c, 0xc9, 0x8b, 0x01,
	0x00, 0x00,
}
