// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/menu.proto

package common

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Menu struct {
	Metadata             *Metadata        `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Url                  string           `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Ico                  string           `protobuf:"bytes,3,opt,name=ico,proto3" json:"ico,omitempty"`
	Enable               bool             `protobuf:"varint,4,opt,name=enable,proto3" json:"enable,omitempty"`
	SubMenus             map[int32]string `protobuf:"bytes,5,rep,name=sub_menus,json=subMenus,proto3" json:"sub_menus,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Policy               *Policy          `protobuf:"bytes,6,opt,name=policy,proto3" json:"policy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Menu) Reset()         { *m = Menu{} }
func (m *Menu) String() string { return proto.CompactTextString(m) }
func (*Menu) ProtoMessage()    {}
func (*Menu) Descriptor() ([]byte, []int) {
	return fileDescriptor_11feaaa00ea0b31a, []int{0}
}

func (m *Menu) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Menu.Unmarshal(m, b)
}
func (m *Menu) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Menu.Marshal(b, m, deterministic)
}
func (m *Menu) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Menu.Merge(m, src)
}
func (m *Menu) XXX_Size() int {
	return xxx_messageInfo_Menu.Size(m)
}
func (m *Menu) XXX_DiscardUnknown() {
	xxx_messageInfo_Menu.DiscardUnknown(m)
}

var xxx_messageInfo_Menu proto.InternalMessageInfo

func (m *Menu) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Menu) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Menu) GetIco() string {
	if m != nil {
		return m.Ico
	}
	return ""
}

func (m *Menu) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

func (m *Menu) GetSubMenus() map[int32]string {
	if m != nil {
		return m.SubMenus
	}
	return nil
}

func (m *Menu) GetPolicy() *Policy {
	if m != nil {
		return m.Policy
	}
	return nil
}

type MenuTree struct {
	RootMenu             *Menu    `protobuf:"bytes,1,opt,name=rootMenu,proto3" json:"rootMenu,omitempty"`
	SubMenuIds           []int32  `protobuf:"varint,2,rep,packed,name=sub_menu_ids,json=subMenuIds,proto3" json:"sub_menu_ids,omitempty"`
	SubMenus             []*Menu  `protobuf:"bytes,3,rep,name=sub_menus,json=subMenus,proto3" json:"sub_menus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MenuTree) Reset()         { *m = MenuTree{} }
func (m *MenuTree) String() string { return proto.CompactTextString(m) }
func (*MenuTree) ProtoMessage()    {}
func (*MenuTree) Descriptor() ([]byte, []int) {
	return fileDescriptor_11feaaa00ea0b31a, []int{1}
}

func (m *MenuTree) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MenuTree.Unmarshal(m, b)
}
func (m *MenuTree) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MenuTree.Marshal(b, m, deterministic)
}
func (m *MenuTree) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MenuTree.Merge(m, src)
}
func (m *MenuTree) XXX_Size() int {
	return xxx_messageInfo_MenuTree.Size(m)
}
func (m *MenuTree) XXX_DiscardUnknown() {
	xxx_messageInfo_MenuTree.DiscardUnknown(m)
}

var xxx_messageInfo_MenuTree proto.InternalMessageInfo

func (m *MenuTree) GetRootMenu() *Menu {
	if m != nil {
		return m.RootMenu
	}
	return nil
}

func (m *MenuTree) GetSubMenuIds() []int32 {
	if m != nil {
		return m.SubMenuIds
	}
	return nil
}

func (m *MenuTree) GetSubMenus() []*Menu {
	if m != nil {
		return m.SubMenus
	}
	return nil
}

type MenuRequest struct {
	RootMenuId           int32    `protobuf:"varint,1,opt,name=root_menu_id,json=rootMenuId,proto3" json:"root_menu_id,omitempty"`
	RootMenuName         string   `protobuf:"bytes,2,opt,name=root_menu_name,json=rootMenuName,proto3" json:"root_menu_name,omitempty"`
	Menu                 *Menu    `protobuf:"bytes,3,opt,name=menu,proto3" json:"menu,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MenuRequest) Reset()         { *m = MenuRequest{} }
func (m *MenuRequest) String() string { return proto.CompactTextString(m) }
func (*MenuRequest) ProtoMessage()    {}
func (*MenuRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_11feaaa00ea0b31a, []int{2}
}

func (m *MenuRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MenuRequest.Unmarshal(m, b)
}
func (m *MenuRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MenuRequest.Marshal(b, m, deterministic)
}
func (m *MenuRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MenuRequest.Merge(m, src)
}
func (m *MenuRequest) XXX_Size() int {
	return xxx_messageInfo_MenuRequest.Size(m)
}
func (m *MenuRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MenuRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MenuRequest proto.InternalMessageInfo

func (m *MenuRequest) GetRootMenuId() int32 {
	if m != nil {
		return m.RootMenuId
	}
	return 0
}

func (m *MenuRequest) GetRootMenuName() string {
	if m != nil {
		return m.RootMenuName
	}
	return ""
}

func (m *MenuRequest) GetMenu() *Menu {
	if m != nil {
		return m.Menu
	}
	return nil
}

func init() {
	proto.RegisterType((*Menu)(nil), "common.Menu")
	proto.RegisterMapType((map[int32]string)(nil), "common.Menu.SubMenusEntry")
	proto.RegisterType((*MenuTree)(nil), "common.MenuTree")
	proto.RegisterType((*MenuRequest)(nil), "common.MenuRequest")
}

func init() { proto.RegisterFile("common/menu.proto", fileDescriptor_11feaaa00ea0b31a) }

var fileDescriptor_11feaaa00ea0b31a = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x71, 0x62, 0xdc, 0x49, 0xa8, 0xca, 0x16, 0x90, 0xe5, 0x93, 0x15, 0x21, 0x64, 0x04,
	0x38, 0x22, 0x1c, 0x40, 0x70, 0x02, 0x8a, 0x50, 0x0f, 0x45, 0x68, 0xa1, 0x17, 0x2e, 0xd5, 0x3a,
	0x9e, 0x16, 0x0b, 0xdb, 0x6b, 0xbc, 0xbb, 0xa0, 0x1c, 0xf9, 0x03, 0xfc, 0x32, 0x7e, 0x14, 0xda,
	0xaf, 0xb4, 0xe9, 0xa9, 0x39, 0xed, 0xce, 0x9b, 0xf7, 0x66, 0xde, 0xb3, 0xb5, 0x70, 0x77, 0xc5,
	0xdb, 0x96, 0x77, 0x8b, 0x16, 0x3b, 0x55, 0xf4, 0x03, 0x97, 0x9c, 0x44, 0x16, 0x4a, 0x0f, 0x5d,
	0xab, 0xe7, 0x4d, 0xbd, 0x5a, 0xdb, 0x66, 0x7a, 0x7f, 0xc3, 0x97, 0xac, 0x62, 0x92, 0x59, 0x78,
	0xfe, 0x77, 0x04, 0xe3, 0x13, 0xec, 0x14, 0x79, 0x0a, 0xb1, 0x6f, 0x25, 0x41, 0x16, 0xe4, 0xd3,
	0xe5, 0x41, 0x61, 0x25, 0xc5, 0x89, 0xc3, 0xe9, 0x86, 0x41, 0x0e, 0x20, 0x54, 0x43, 0x93, 0x8c,
	0xb2, 0x20, 0xdf, 0xa3, 0xfa, 0xaa, 0x91, 0x7a, 0xc5, 0x93, 0xd0, 0x22, 0xf5, 0x8a, 0x93, 0x07,
	0x10, 0x61, 0xc7, 0xca, 0x06, 0x93, 0x71, 0x16, 0xe4, 0x31, 0x75, 0x15, 0x79, 0x09, 0x7b, 0x42,
	0x95, 0x67, 0xda, 0xb8, 0x48, 0x26, 0x59, 0x98, 0x4f, 0x97, 0xe9, 0xe5, 0xaa, 0x4e, 0x15, 0x5f,
	0x54, 0xa9, 0x4f, 0xf1, 0xa1, 0x93, 0xc3, 0x9a, 0xc6, 0xc2, 0x95, 0xe4, 0x11, 0x44, 0x36, 0x52,
	0x12, 0x19, 0x83, 0xfb, 0x5e, 0xf5, 0xd9, 0xa0, 0xd4, 0x75, 0xd3, 0x37, 0x70, 0x67, 0x6b, 0x84,
	0xf6, 0xf6, 0x03, 0xd7, 0x26, 0xd6, 0x84, 0xea, 0x2b, 0xb9, 0x07, 0x93, 0x5f, 0xac, 0x51, 0xe8,
	0x12, 0xd8, 0xe2, 0xf5, 0xe8, 0x55, 0x30, 0xff, 0x13, 0x40, 0xac, 0xa5, 0x5f, 0x07, 0x44, 0x92,
	0x43, 0x3c, 0x70, 0x2e, 0x75, 0xed, 0x3e, 0xca, 0xec, 0xaa, 0x53, 0xba, 0xe9, 0x92, 0x0c, 0x66,
	0x3e, 0xd4, 0x59, 0x5d, 0x89, 0x64, 0x94, 0x85, 0xf9, 0x84, 0x82, 0xf3, 0x7e, 0x5c, 0x09, 0xf2,
	0xf8, 0x6a, 0xec, 0xd0, 0xc4, 0xbe, 0x36, 0xcc, 0x07, 0x9d, 0xff, 0x86, 0xa9, 0x41, 0xf0, 0xa7,
	0x42, 0x21, 0xf5, 0x6c, 0xbd, 0xc7, 0x0f, 0x77, 0x39, 0xc0, 0xef, 0x3e, 0xae, 0xc8, 0x43, 0xd8,
	0xbf, 0x64, 0x74, 0xac, 0xf5, 0xb9, 0x66, 0x9e, 0xf3, 0x89, 0xb5, 0x48, 0x32, 0x18, 0x6b, 0x82,
	0xf9, 0x47, 0xd7, 0x97, 0x9b, 0xce, 0xf2, 0x5f, 0x00, 0xe3, 0xf7, 0xf4, 0xf4, 0x88, 0x14, 0x70,
	0xfb, 0x6d, 0x55, 0x99, 0x64, 0x87, 0x5b, 0x3c, 0x6b, 0x29, 0xdd, 0x12, 0xcf, 0x6f, 0x69, 0xfe,
	0x47, 0x94, 0x37, 0xe7, 0x3f, 0x07, 0x38, 0xed, 0x2b, 0x26, 0x71, 0x27, 0xc9, 0x11, 0x36, 0xb8,
	0x83, 0xe4, 0xdd, 0xb3, 0x6f, 0x4f, 0x2e, 0x6a, 0xf9, 0x5d, 0x95, 0x1a, 0x5f, 0x60, 0x73, 0xce,
	0x87, 0x0b, 0x7d, 0xf4, 0x0d, 0x93, 0xe7, 0x7c, 0x68, 0x17, 0xe6, 0x0d, 0x88, 0x85, 0x55, 0x95,
	0x91, 0x29, 0x5f, 0xfc, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x2b, 0x26, 0x50, 0x5b, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CRUDClient is the client API for CRUD service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CRUDClient interface {
	AddMenu(ctx context.Context, in *MenuRequest, opts ...grpc.CallOption) (*Menu, error)
	GetMenu(ctx context.Context, in *MenuRequest, opts ...grpc.CallOption) (*Menu, error)
	UpdateMenu(ctx context.Context, in *MenuRequest, opts ...grpc.CallOption) (*Menu, error)
	DeleteMenu(ctx context.Context, in *MenuRequest, opts ...grpc.CallOption) (*Menu, error)
}

type cRUDClient struct {
	cc *grpc.ClientConn
}

func NewCRUDClient(cc *grpc.ClientConn) CRUDClient {
	return &cRUDClient{cc}
}

func (c *cRUDClient) AddMenu(ctx context.Context, in *MenuRequest, opts ...grpc.CallOption) (*Menu, error) {
	out := new(Menu)
	err := c.cc.Invoke(ctx, "/common.CRUD/AddMenu", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cRUDClient) GetMenu(ctx context.Context, in *MenuRequest, opts ...grpc.CallOption) (*Menu, error) {
	out := new(Menu)
	err := c.cc.Invoke(ctx, "/common.CRUD/GetMenu", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cRUDClient) UpdateMenu(ctx context.Context, in *MenuRequest, opts ...grpc.CallOption) (*Menu, error) {
	out := new(Menu)
	err := c.cc.Invoke(ctx, "/common.CRUD/UpdateMenu", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cRUDClient) DeleteMenu(ctx context.Context, in *MenuRequest, opts ...grpc.CallOption) (*Menu, error) {
	out := new(Menu)
	err := c.cc.Invoke(ctx, "/common.CRUD/DeleteMenu", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CRUDServer is the server API for CRUD service.
type CRUDServer interface {
	AddMenu(context.Context, *MenuRequest) (*Menu, error)
	GetMenu(context.Context, *MenuRequest) (*Menu, error)
	UpdateMenu(context.Context, *MenuRequest) (*Menu, error)
	DeleteMenu(context.Context, *MenuRequest) (*Menu, error)
}

func RegisterCRUDServer(s *grpc.Server, srv CRUDServer) {
	s.RegisterService(&_CRUD_serviceDesc, srv)
}

func _CRUD_AddMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRUDServer).AddMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.CRUD/AddMenu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRUDServer).AddMenu(ctx, req.(*MenuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CRUD_GetMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRUDServer).GetMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.CRUD/GetMenu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRUDServer).GetMenu(ctx, req.(*MenuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CRUD_UpdateMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRUDServer).UpdateMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.CRUD/UpdateMenu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRUDServer).UpdateMenu(ctx, req.(*MenuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CRUD_DeleteMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRUDServer).DeleteMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.CRUD/DeleteMenu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRUDServer).DeleteMenu(ctx, req.(*MenuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CRUD_serviceDesc = grpc.ServiceDesc{
	ServiceName: "common.CRUD",
	HandlerType: (*CRUDServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddMenu",
			Handler:    _CRUD_AddMenu_Handler,
		},
		{
			MethodName: "GetMenu",
			Handler:    _CRUD_GetMenu_Handler,
		},
		{
			MethodName: "UpdateMenu",
			Handler:    _CRUD_UpdateMenu_Handler,
		},
		{
			MethodName: "DeleteMenu",
			Handler:    _CRUD_DeleteMenu_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common/menu.proto",
}
